name: Guard PRs from fork main
on:
  workflow_call: {}

permissions:
  pull-requests: write
  issues: write

jobs:
  guard:
    if: ${{ github.event_name == 'pull_request_target' && github.event.pull_request.head.repo.fork && github.event.pull_request.head.ref == 'main' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v7
        with:
          script: |
            const pr = context.payload.pull_request;
            const commenter = pr.user.login;
            const body = [
              `Hi @${commenter}, thanks for the PR!`,
              '',
              'This PR was opened from the `main` branch of your fork. That prevents maintainers from safely pushing edits.',
              '',
              'Please create a new branch in your fork (e.g. `feat/my-change`) and open a new PR.',
              '',
              'Closing this PR to keep things tidy.'
            ].join('\n');

            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: pr.number,
              body
            });

            await github.rest.pulls.update({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: pr.number,
              state: 'closed'
            });
