name: Guard PRs from fork main

on:
  pull_request_target:
    types: [opened, reopened]

permissions:
  pull-requests: write
  issues: write

jobs:
  close-if-fork-main:
    if: ${{ github.event.pull_request.head.repo.fork && github.event.pull_request.head.ref == 'main' }}
    runs-on: ubuntu-latest
    steps:
      - name: Comment and close
        uses: actions/github-script@v7
        with:
          script: |
            const pr = context.payload.pull_request;
            const commenter = pr.user.login;
            const body = [
              `Hi @${commenter}, thanks for the PR!`,
              '',
              'This PR was opened from the `main` branch of your fork. That setup prevents maintainers from safely pushing edits.',
              '',
              'Please:',
              '1. Create a new branch in your fork (for example `feat/my-change`).',
              '2. Push your commits to that branch.',
              '3. Open a new PR from that branch.',
              '',
              'Closing this PR to keep things tidy. Feel free to open a new one.'
            ].join('\n');

            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: pr.number,
              body
            });

            await github.rest.pulls.update({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: pr.number,
              state: 'closed'
            });
